Add RENCI 4.2.7 engineering build
Add a script to advance the database internal object ID sequence > 32
bit unsigned.

Add a new Makefile target.

diff --git a/docker/irods/ubuntu/16.04/Dockerfile.engineering b/docker/irods/ubuntu/16.04/Dockerfile.engineering
--- a/docker/irods/ubuntu/16.04/Dockerfile.engineering
+++ b/docker/irods/ubuntu/16.04/Dockerfile.engineering
@@ -4,6 +4,8 @@ FROM $BASE_IMAGE
 # This default is the latest usable version
 ARG IRODS_VERSION="4.2.7"
 
+ARG ENG_BUILD_URL
+
 ENV DEBIAN_FRONTEND=noninteractive
 
 WORKDIR /opt/docker/irods
@@ -33,21 +35,20 @@ ENV LANG=en_GB.UTF-8 \
     LC_ALL=en_GB.UTF-8 \
     TZ=/Etc/UTC
 
+# Required to get the externals packages
 RUN curl -sSL https://packages.irods.org/irods-signing-key.asc | apt-key add - && \
     echo "deb [arch=amd64] https://packages.irods.org/apt $(lsb_release -sc) main" | \
     tee /etc/apt/sources.list.d/renci-irods.list && \
-    apt-get update && \
-    apt-get install -q -y --no-install-recommends \
-    irods-server="$IRODS_VERSION" \
-    irods-runtime="$IRODS_VERSION" \
-    irods-database-plugin-postgres="$IRODS_VERSION" \
-    irods-icommands="$IRODS_VERSION" && \
-    apt-get install -q -y -f && \
-    unattended-upgrade -v && \
-    apt-get remove -q -y unattended-upgrades && \
-    apt-get autoremove -q -y && \
-    apt-get clean -q -y && \
-    rm -rf /var/lib/apt/lists/*
+    apt-get update
+
+RUN test -n "$ENG_BUILD_URL" || \
+    { echo "ENG_BUILD_URL build argument is required" >&2; exit 1; }
+
+RUN curl -fsSL -o sanger_engineering_build-irods_4.2.7.tar.gz "$ENG_BUILD_URL" && \
+    tar xvf sanger_engineering_build-irods_4.2.7.tar.gz && \
+    md5sum sanger_engineering_build_4.2.7/*.deb
+
+RUN apt-get update && apt-get install -y ./sanger_engineering_build_4.2.7/*.deb
 
 RUN /opt/docker/irods/scripts/create_database.sh && \
     /opt/docker/irods/scripts/configure_irods.sh && \
